apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../kubesphere-base
images:
  - name: gcr.io/k8s-staging-metrics-server/metrics-server
    newName: kubesphere/metrics-server
    newTag: v0.4.2

